apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: us-east-1

vpc:
  id: "vpc-030e68dc5674d505a"
  subnets:
    public:
      us-east-1a:
        id: "subnet-0d6aa917954045829"
      us-east-1b:
        id: "subnet-0543a2ca8849addcb"

nodeGroups:
- name: my-nodes
  instanceType: t2.medium
  desiredCapacity: 2
  volumeSize: 20
  ssh:
    allow: true
